In [3]:
import numpy as np
fp = "Dataset.txt"
data = np.genfromtxt(fp, skip_header=1, usecols=(0, 1, 2, 3))



[[1973.    18.1   24.7   12.8]
 [1974.    18.6   25.5   13. ]
 [1975.    18.5   25.9   12. ]
 [1976.    17.8   25.6   11.1]
 [1977.    18.8   26.4   12. ]
 [1978.    17.8   25.4   11.1]
 [1979.    17.5   24.9   10.9]
 [1980.    19.1   27.    12.1]
 [1981.    18.4   25.8   11.7]
 [1982.    18.3   25.6   12.1]
 [1983.    17.3   24.2   11.1]
 [1984.    18.6   26.    12.6]
 [1985.    18.3   25.4   12.1]
 [1986.    18.8   25.8   12.9]
 [1987.    18.5   25.9   11.8]
 [1988.    18.7   26.4   12.1]
 [1989.    17.9   25.4   11.8]
 [1990.    19.3   26.6   12.5]
 [1991.    18.7   25.8   12.3]
 [1992.    18.7   25.6   12.5]
 [1993.    18.4   25.3   12.2]
 [1994.    18.9   25.8   12.5]
 [1995.    18.8   26.    12.2]
 [1996.    18.4   25.5   12.5]
 [1997.    18.    23.8   13.3]
 [1998.    20.3   26.1   15.5]
 [1999.    20.3   26.9   14.7]
 [2000.    19.7   26.4   13.7]
 [2001.    18.6   25.1   12.8]
 [2002.     nan    nan    nan]
 [2003.    18.9   26.1   12.7]
 [2004.    19.1   25.6   13.4]
 [2005. 

#All Data

In [ ]:
data

In [ ]:
date=data[:,0]
# print (date)
t_AVG = data[:,1]
t_MIN = data[:,2]
t_MAX = data[:,3]
# print (t_AVG)
# print (t_MIN)
# print (t_MAX)
date_mask = np.isfinite(date)

# print("Number of years:", np.count_nonzero(date_mask))

missing_date_mask = ~np.isfinite(date)

# print("Number of missing years:", np.count_nonzero(missing_date_mask))

t_AVG_mask = np.isfinite(t_AVG)
# print("Number of avg temps:", np.count_nonzero(t_AVG_mask))

missing_t_MAX_mask = ~np.isfinite(t_MAX)
# print("NUmber of misisng T_MAX values:", np.count_nonzero(missing_t_MAX_mask))
tmax_mask = np.isfinite(t_MAX)

tmax_clean = t_MAX[tmax_mask]
print (tmax_clean)
date_clean = date[tmax_mask]

tmax_total = tmax_clean[(date_clean >= 1973 & (date_clean < 2010))]

#Average Temperature (*C)

In [4]:
tmax_total.mean()

12.808695652173917