In [74]:
import numpy as np
from numpy import genfromtxt

import csv

def readCSVToNumpyArray(dataset):
        values = [[]]
        with open(dataset) as f:
            counter = 0
            for i in csv.reader(f):
                for j in i:
                    try:
                        values[counter].append(float(j))
                    except ValueError:
                        values[counter].append(j)
                counter = counter + 1
                values.append([])

        data = np.array(values[:-1],dtype='object')

        return data

numpyArray = readCSVToNumpyArray('02-28-2021.csv')
for i in range(6):

    print(numpyArray[i])


['FIPS' 'Admin2' 'Province_State' 'Country_Region' 'Last_Update' 'Lat'
 'Long_' 'Confirmed' 'Deaths' 'Recovered' 'Active' 'Combined_Key'
 'Incident_Rate' 'Case_Fatality_Ratio']
['' '' '' 'Afghanistan' '2021-03-01 05:23:01' 33.93911 67.709953 55714.0
 2443.0 49333.0 3938.0 'Afghanistan' 143.11937927177527 4.384894281509136]
['' '' '' 'Albania' '2021-03-01 05:23:01' 41.1533 20.1683 107167.0 1796.0
 69773.0 35598.0 'Albania' 3723.921050802696 1.675889033004563]
['' '' '' 'Algeria' '2021-03-01 05:23:01' 28.0339 1.6596 113092.0 2983.0
 78098.0 32011.0 'Algeria' 257.900365106481 2.637675520814912]
['' '' '' 'Andorra' '2021-03-01 05:23:01' 42.5063 1.5218 10866.0 110.0
 10446.0 310.0 'Andorra' 14063.288681809358 1.0123320449107307]
['' '' '' 'Angola' '2021-03-01 05:23:01' -11.2027 17.8739 20807.0 508.0
 19322.0 977.0 'Angola' 63.30807014657095 2.4414860383524775]


In [75]:
countryData = {}
print (len(numpyArray))

for i in range(len(numpyArray)-1):
    countryName = numpyArray[i+1][3]
    countryData[countryName] = [0,0,0,0]

for i in range(len(numpyArray)-1):
    tempArray = np.array(numpyArray[i+1][7:11])
    print(countryData[numpyArray[i+1][3]])
    countryName = numpyArray[i+1][3]
    countryData[countryName] = countryData[countryName] + tempArray
    
     

print(countryData)

3982
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[118.0 3.0 115.0 0.0]
[5298.0 57.0 115.0 5126.0]
[5403.0 57.0 218.0 5128.0]
[6734.0 63.0 1531.0 5140.0]
[7350.0 67.0 2137.0 5146.0]
[7584.0 80.0 2358.0 5146.0]
[28065.0 900.0 22008.0 5157.0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[97082.0 0.0 0.0 97082.0]
[192513.0 0.0 0.0 192513.0]
[275984.0 0.0 0.0 275984.0]
[335515.0 0.0 0.0 335515.0]
[452050.0 0.0 0.0 452050.0]
[557560.0 0.0 0.0 557560.0]
[596004.0 0.0 0.0 596004.0]
[617883.0 0.0 0.0 617883.0]
[658290.0 0.0 0.0 658290.0]
[672449.0 22077.0 0.0 650372.0]
[702436.0 22077.0 0.0 680359.0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[57534.0 998.0 46623.0 9913.0]
[189280.0 3997.0 171930.0 13353.0]
[272943.0 5137.0 232406.0 35400.0]
[588909.0 15997.0 501548.0 71364.0]
[1272946.0 27816.0 1150141.0 94989.0]
[16

TypeError: unsupported operand type(s) for +: 'float' and 'str'